### ISSUE TITLE
[Feature] update dbt-expectations version range

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_hubspot#117]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The latest version out of dbt-expectations is [0.9.0](https://github.com/calogica/dbt-expectations/releases/tag/0.9.0) and this package will force folks to pin to older versions

informed by https://github.com/fivetran/dbt_google_ads_source/issues/44

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-reneeli** [comment]
Included in the latest release!
