### ISSUE TITLE
[Bug] Quickstarts Not Showing in Hubspot connector

### ISSUE THREAD

**Issue by rishi-tripathy** [fivetran/dbt_hubspot#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

As described. Downstream connections seem empty but only for one instance of the hubspot connectors in our account

![Rishi took a Cleanshot - 2024-03-11 at 10 44 48](https://github.com/fivetran/dbt_hubspot/assets/40015320/ef79c0a8-4256-44c0-87cf-16acc2f94224)

### Expected behavior

I'd expect the quickstarts to show as in all the other hubspot connectors in our account

![Rishi took a Cleanshot - 2024-03-11 at 10 52 31](https://github.com/fivetran/dbt_hubspot/assets/40015320/49c8c304-df9d-4409-a288-3335c111d7a9)

### dbt Project configurations

quickstart

### Package versions

quickstart

### What database are you using dbt with?

snowflake

### dbt Version

quickstart

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-jamie** [comment]
Hey there @rishi-tripathy 👋 so in this repository we support the _code_ that Quickstart _uses_, whereas I believe your question is more about Quickstart itself specifically. 

I'd recommend opening a ticket in the Fivetran [support](https://support.fivetran.com/hc/en-us) portal and the Quickstart team can help you better from there
