### ISSUE TITLE
Typo's in readme

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_hubspot#38]
I've noticed a typo in the readme that I'm quite happy to fix if I get the rights to create a PR.    
`hubspot_email_event_spam_report` should be `hubspot_email_event_spam_report_enabled` . As the typo is in the VARs that likely will be copied by folks it would be good to fix.
Also this line is a duplicate:   hubspot_email_event_click_enabled: false

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann thanks for catching these and we appreciate you letting us know so other folks don't copy and paste the wrong variable configs in their `dbt_project.yml`! 

I implemented these fixes within the open PR #37
