### ISSUE TITLE
Freshness checks fail for sources whose tables are excluded from sync

### ISSUE THREAD

**Issue by joellabes** [fivetran/dbt_hubspot#41]
We have disabled the email events with `hubspot_email_event_enabled: false` because we're not syncing them. The freshness test doesn't seem to have been disabled though as we get this error message:
```
Database Error in source email_event (models/src_hubspot.yml)
  relation "ft_hubspot.email_event" does not exist
```

Is there a way to stop the table from being freshness tested? I can't overwrite it with null like I could if I controlled the `schema.yml` file. 

We also disabled another table (`contact_property_history`) after initially enabling it, and I suspect that this table will also start appearing as stale sometime soon.

**Comment by fivetran-kristin** [comment]
Thanks for creating this @joellabes 

(internal note for fivetran) -- For future reference, these may be good resources:
- https://github.com/fishtown-analytics/dbt/issues/2428
- https://github.com/fishtown-analytics/dbt/blob/9d0eab630511723cd0bc328f6f11d3ffe6c8f879/core/dbt/include/global_project/macros/adapters/common.sql#L287-L303

**Comment by fivetran-jamie** [comment]
hey there @joellabes -- i think we've come up with a neat solution for this. could you run freshness tests using the following branch of the package to test it out? if `hubspot_email_event_enabled` is set to false, freshness tests should "pass" for disabled source tables
```yml
# your project's packages.yml
  - git: https://github.com/fivetran/dbt_hubspot.git
    revision: disable_freshness
```

**Comment by fivetran-jamie** [comment]
hey just pushed a [release](https://github.com/fivetran/dbt_hubspot_source/releases/tag/v0.3.3) of the source package with this fix! the transform package already references the [most up-to-date version](https://github.com/fivetran/dbt_hubspot/blob/master/packages.yml) of the source package, so you should automatically see this fix next time you run dbt deps

**Comment by joellabes** [comment]
Hey @fivetran-jamie this is great, thanks! Sorry for the late reply - I was on leave. Will let you know if we run into any issues 🌟
