### ISSUE TITLE
BUG - Typo in email_sends model

### ISSUE THREAD

**Issue by bthomson22** [fivetran/dbt_hubspot#48]
**Are you a current Fivetran customer?** 

Brandon Thomson, Marketing Analytics Engineer @ dbt Labs

**Describe the bug**

This is a simple issue - in the `email_sends` model the field `was_deferred` is spelled `was_deffered`. By fixing this typo, the field will be consistent across other models.

**Steps to reproduce**

N/A

**Expected behavior**

N/A

**Project variables configuration**

```N/A
```

**Package Version**

```packages:
  - package: fivetran/hubspot_source
    version: [">=0.3.0", "<0.4.0"]
```

**Warehouse**

 
- [ ] BigQuery
- [ ] Redshift
- [X] Snowflake
- [ ] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Additional context**
 

**Screenshots**

**Please indicate the level of urgency** 

This isn't urgent at all. Just wanted to make the team aware of it because it does create some small confusion.

**Are you interested in contributing to this package?** 

- [X] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this fixed. 
- [ ] No, I'd prefer if someone else fixed this.  I don't have the time and/or don't know what the root cause of the problem is.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for opening this issue. This typo has been resolved in the latest `v0.4.0` release of the hubspot package!
