### ISSUE TITLE
engagement_meeting.meeting_outcome Missing from source table

### ISSUE THREAD

**Issue by fivetran-kristin** [fivetran/dbt_hubspot#5]
We need to figure out a sophisticate way to account for these scenarios.  As a short-term solution, we can remove this field from the model.

**Comment by fivetran-jamie** [comment]
was this solved by introducing the staging model [macros](https://github.com/fivetran/dbt_hubspot_source/blob/master/macros/get_engagement_meeting_columns.sql)?

**Comment by fivetran-kristin** [comment]
Yes, thank you!
