### ISSUE TITLE
QUESTION - what does the Campaign ContentId relate to?

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_hubspot#52]
**Are you a Fivetran customer?** 
Yes, Chistoph, Sustain.life

**Your Question**
I'm seeing content_id in the campaign
      - name: content_id
        description: The ID of the content.

What is this referring to?  I would have expected a table with contents which i don't see.  My hope is to see the email body somewhere?

**Additional context**
see above

**Please indicate the level of urgency and business impact of this request** 
medium...  I'd like to avoid our dev team building a custom call into hubspot just to get the email body.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann you are correct that the `content_id` relates to the body of the email. However, after chatting with our internal team it seems we do not bring the content object into our existing schema for the HubSpot connector.

I see you are looking at possibly building out a custom call to HubSpot for this object. Does it seem this information would be useful? It could work to possibly open a feature request ticket within the [Fivetran Support portal](https://support.fivetran.com/hc/en-us) to ask for this feature to be included in a future version of the HubSpot connector.

**Comment by leinemann** [comment]
Ok, great, thanks for looking into this @fivetran-joemarkiewicz.  I've raised this feature request: https://support.fivetran.com/hc/en-us/community/posts/4405935477015-Connector-Improvement-Bring-in-Content-object-from-hubspot-to-be-able-to-resolve-the-content-id

**Comment by fivetran-joemarkiewicz** [comment]
Of course! Thanks for opening the feature request. I will close this issue as you have now opened the new ticket on our support portal. Please feel free to reopen this ticket or open a new one if you have any future questions. 

Thanks 😄
