### ISSUE TITLE
FEATURE - Ability to shut off history tables individually.

### ISSUE THREAD

**Issue by brettkobo** [fivetran/dbt_hubspot#54]
**Are you a Fivetran customer?** 
Brett Kobold, Director of Analytics @ Retina.AI

**Is your feature request related to a problem? Please describe.**
Kinda. I would like the option to disable the history tables. I currently have them turned off in Fivetran to save on rows as I do not need them at the moment for the type of reporting I am doing.

**Describe the solution you'd like**
I would love a pattern similar to exactly how the other tables are enabled but just for the history tables. Unless those tables are need to build the core tables which I am unaware of at the moment. The only way I say to shut them off was to turn of the full table.

**Describe alternatives you've considered**
I have thought about just deleteing or commenting of those models in my local repo.

**Additional context**

**Please indicate the level of urgency and business impact of this request** 
Not urgent but is just says my DBT run has failed because I do not have the history tables.

**Are you interested in contributing to this package?** 

- [X ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented.

**Comment by brettkobo** [comment]
Hey Joe!

Thanks for responding. I would love to learn more how these packages are built. I can't guarantee I can do it but I will give it shot. If you haven't seen me push a PR by the time you get started on it, assume I wasn't able to do it. I just started with with DBT today but have been wanting to get deeper into it.

- brett

**Comment by codingcyclist** [comment]
Hey @fivetran-joemarkiewicz :) Is this issue still active? We're also having a use case where we'd like to turn off the property history tables for customers, companies, and deals individually

**Comment by fivetran-joemarkiewicz** [comment]
Hi @codingcyclist this is still active although we have put this on the back burner to address higher priority items. That being said, we are planning to apply some larger updates to HubSpot in the current quarter and believe this may be a feasible feature to incorporate into the upcoming updates.

Just to confirm, you would be looking to essentially filter out the historical records from these models. Or are you looking to do something else?

**Comment by codingcyclist** [comment]
@fivetran-joemarkiewicz It would be fantastic if you could include it in the Q4 sprint! And yes, you're exactly right: we'd want the `company` and `deal` models to not depend on `company_property_history` / `deal_property_history`. 

It even looks like one could copy the existing "toggle" logic from the `contact` model, where the `hubspot_contact_property_enabled` config variable can be used to de-activate historical records.

**Comment by fivetran-jamie** [comment]
hey hey! this is in the latest [version](https://github.com/fivetran/dbt_hubspot/releases/tag/v0.14.0) of the package

the exact variable names are 
- `hubspot_company_property_history_enabled`
- `hubspot_contact_property_history_enabled`
- `hubspot_deal_property_history_enabled`
