### ISSUE TITLE
FEATURE - databricks and postgres compatibility

### ISSUE THREAD

**Issue by fivetran-jamie** [fivetran/dbt_hubspot#55]
**Are you a Fivetran customer?** 

nope!

**Is your feature request related to a problem? Please describe.**
 
No, just want to roll out postgres + databricks compatibility for our most popular packages. 

**Describe the solution you'd like**
 
make it compatible with both!

**Please indicate the level of urgency and business impact of this request** 

Does not seem urgent, but did come out of a customer request on dbt slack

**Are you interested in contributing to this package?** 

- [x] Yes, I can do this and open a PR for your review.
- [ ] Possibly, but I'm not quite sure how to do this. I'd be happy to do a live coding session with someone to get this work implemented. 
- [ ] No, I'd prefer if someone else did this.  I don't have the time and/or don't know how to incorporate the changes necessary.

**Comment by fivetran-joemarkiewicz** [comment]
- [X] Postgres compatibility
- [ ] Databricks compatibility
