### ISSUE TITLE
[Bug] valid_to within hubspot__company_history needs to be adjusted

### ISSUE THREAD

**Issue by fivetran-joemarkiewicz** [fivetran/dbt_hubspot#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The current logic for the `valid_to` field within the `hubspot__company_history` model is as follows:

https://github.com/fivetran/dbt_hubspot/blob/2c8c15a2fb56b59a47d758ccaa0046b6c552c136/models/sales/history/hubspot__company_history.sql#L17

However, this model is intended to represent the historical view of the change of properties. Therefore, we will want to instead adjust the partition to include both `company_id` and `field_name` to appropriately capture the historical changes of the company properties.

### Relevant error log or model output

```shell
N/A
```

### Expected behavior

The model captures the proper `valid_from` and `valid_to` for each historical property change for the hubspot company.

### dbt Project configurations

N/A

### Package versions

packages:
  - package: fivetran/hubspot
    version: [">=0.5.0", "<0.6.0"]

### What database are you using dbt with?

postgres, redshift, snowflake, bigquery

### dbt Version

Core:
  - installed: 1.1.0
  - latest:    1.1.0 - Up to date!

Plugins:
  - bigquery: 1.1.0 - Up to date!

### Additional Context

N/A

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by ramiouanes** [comment]
Hello @fivetran-joemarkiewicz ,

I just wanted to inform you that this issue was also found on the Deal & Contact history models.
Would it be possible to fix those too?

It would be great to have a timeline on this too, as we are currently unable to deploy our dbt logic on PROD and schedule it through Fivetran. We have to launch our code locally and manually until this is fixed. Meaning that this bug is currently blocking a PROD delivery.

Thank you for your help.

**Comment by fivetran-joemarkiewicz** [comment]
HI @ramiouanes thanks for highlighting that for us!

We will most likely be picking this issue up in our next sprint (starting next Wednesday 6/1 and ending 6/15). However, if you would like a more immediate fix, you can actually fork this repo and apply the changes highlighted to your fork. You can then install your forked repo instead of the official version of this package using the [git package installation method](https://docs.getdbt.com/docs/building-a-dbt-project/package-management#git-packages).

If this works for you, we are always excited and encourage community made PRs! If not, we will be able to address this in the next release of the package which we hope to have live by the end of our next sprint.

**Comment by fivetran-sheringuyen** [comment]
Happy Tuesday @ramiouanes! I just cut a release for dbt_hubspot v0.5.3 and the updates outlined in this PR should be ready to go in the next couple of hours, please watch out for it on the dbt package hub! :)
