### ISSUE TITLE
_fivetran_deleted filtering issues

### ISSUE THREAD

**Issue by ryan-tangocard** [fivetran/dbt_hubspot#7]
I noticed that the `hubspot\models\marketing\hubspot__contacts.sql` wasn't producing any results and after doing some digging see that `hubspot_source\models\stg_hubspot__contact.sql` is filtering on `where _fivetran_deleted is null`. 

As I am writing this - I did a quick search in the Release Notes for this connector and see that `CONTACT` table tracks deletions as of Aug 2020 and we added this a few weeks ago - so that would be why. 😄 

So now that some tables support the `_fivetran_deleted` column, is it possible for this to be `null` for any table? I reviewed a couple of the tables not supported and also did not see results when filtering out `null`. I think in my experience with Fivetran connectors as soon as support is added (even if not fully) it will no longer show `null` even in unsupported tables?

**Comment by fivetran-jamie** [comment]
hey there - thanks for surfacing this, and apologies for the wait! this should be solved by the most recent [release](https://github.com/fivetran/dbt_hubspot_source/releases/tag/v0.2.0) of the source package, which now filters on `where not coalesce(_fivetran_deleted, false)` 😄
