### ISSUE TITLE
[Feature] Add custom properties to the base models

### ISSUE THREAD

**Issue by moseleyi** [fivetran/dbt_hubspot#73]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

How to add custom properties to, for example, Deal object. The package creates a transformation with basic values only

### Are you interested in contributing this feature?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [X] No.

**Comment by fivetran-joemarkiewicz** [comment]
HI @moseleyi thank you so much for creating this feature request. Would you be able to elaborate a bit more in regards to what the custom properties are that you detailed above?
