### ISSUE TITLE
Disable all Ticket models

### ISSUE THREAD

**Issue by moseleyi** [fivetran/dbt_hubspot#90]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

I would like to disable all ticket models 

### Are you interested in contributing this feature?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @moseleyi thank you for opening this issue. We actually have a variable that should allow for the disabling of all the ticket models that are generated from the source package. You should be able to add the following variable included in our [README](https://github.com/fivetran/dbt_hubspot#step-4-disable-models-for-non-existent-sources) to disable all ticket models:

```yml
vars:
    hubspot_service_enabled: false
```

Let me know if adding this variable does the trick!

**Comment by moseleyi** [comment]
Ahh okay, I didn't know what "hubspot_service" entails as I couldn't find any references to Tickets. I will have a look

**Comment by fivetran-joemarkiewicz** [comment]
That is a great point, we should probably update our README to highlight that service in this context pertains to the ticket models.

**Comment by moseleyi** [comment]
That would be great. Of course disabling the wervice worked. Thanks @fivetran-joemarkiewicz
