### ISSUE TITLE
[Bug] Removal of deleted record filter resulting in uniqueness test failures

### ISSUE THREAD

**Issue by kcraig-ats** [fivetran/dbt_hubspot#93]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Updating to version 0.8.0 of the HubSpot package resulted in uniqueness test failures. I read in [dbt_hubspot_source #96](https://github.com/fivetran/dbt_hubspot_source/pull/96) that the methods `where not coalesce(is_deleted, false)` and `where not coalesce(_fivetran_deleted, false)` were removed from a number of models to allow for greater flexibility. In testing this does appear to be the cause of the failures. The records that are failing have different deleted flag values. Each set of duplicates has one false flag and the remaining flags are true. Note, I have contact merge auditing enabled and tested it to rule it out as the cause.  In my case, this was specific to email events but seems like it might apply to other models where the filter was removed. 

### Expected behavior

Uniqueness tests should pass.

### dbt Project configurations

n/a

### Package versions

0.8.0

### What database are you using dbt with?

redshift

### dbt Version

1.3

### Additional Context

[Discussion](https://getdbt.slack.com/archives/C01D1R2JLLA/p1674584258619629) with Jamie in dbt slack

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by bdtoole** [comment]
Adding that we're experiencing the same issue on Snowflake, also with email events (`models/marketing/email_events/email_events.yml`) on the `is_contact_deleted` column

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the note @bdtoole! 

Our team is currently working on an update to the downstream tests to account for this change. I will post back once we have an update.

**Comment by fivetran-jamie** [comment]
@bdtoole @kcraig-ats just to confirm, are y'all only seeing the failures in the `models/marketing/email_events` models? or anywhere else as well?

**Comment by kcraig-ats** [comment]
@fivetran-jamie confirming it's just `email_events` for me, but I also don't have `hubspot_deal_enabled` enabled and tickets are not in use.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @kcraig-ats thanks for sharing the additional details here on the tests you are seeing experiencing the failures.

I have been able to open a PR that I believe should address the issue you are experiencing. Would you be able to test the following version of the package (you can replace the normal package dependency in your packages.yml with the following):

```yml
packages:
  - git: https://github.com/fivetran/dbt_hubspot.git
    revision: bugfix/uniqueness-test-adjustment
    warn-unpinned: false 
```

Let me know if using this version of the package addresses the original issue you started seeing after upgrading. Thanks!

**Comment by kcraig-ats** [comment]
@fivetran-joemarkiewicz Yep, that fixed the issue! TY!!

**Comment by bdtoole** [comment]
Confirming that the issue seems fixed for us, too!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks all for your help in raising this issue to our team. We have since been able to address the issue in the latest release of the dbt_hubspot package (`v0.8.2`). Feel free to upgrade to see the test failures resolved.

As a result, I will close out this issue. Please feel free to reopen if the issue persists.
