### ISSUE TITLE
[Feature] Ability to filter out is_filtered_event events

### ISSUE THREAD

**Issue by skalepp-parachutehome** [fivetran/dbt_hubspot#96]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

In HubSpot, there is the ability to filter out events. Ideally, you could have the ability to filter out these events and any upstream models that have this flag within the dbt_project.yml file.

### Describe alternatives you've considered

Unfortunately, there isn't another alternative. I did attend office hours and spoke to the team and we agreed this might make sense as a feature.

### Are you interested in contributing this feature?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-avinash** [comment]
Thanks for explaining it all out @skalepp-parachutehome, scheduling time with us to debug in office hours, and creating an issue on our `dbt_hubspot` package. 

We encourage you to work on this in your end and submit a PR (fork the repo and open the PR off the changes,[ see here for details](https://discourse.getdbt.com/t/contributing-to-an-external-dbt-package/657)), as this can potentially expedite shipping this issue. Let us know if you have any questions!

**Comment by ron-eventgroove** [comment]
I also have a need for the same feature. As a marketer, I appreciate the preconfigured reporting tables, however without the ability to filter out these events or have the events pre-filtered (since these are reporting tables, these events are not required), the tables are not usable. Key metrics are incorrect.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for sharing your experience and desire for the feature @ron-eventgroove!

@skalepp-parachutehome have you been able to start working on a PR? If not, my team will look to fold this feature update into our next upcoming sprint.

Thanks!

**Comment by skalepp-parachutehome** [comment]
@fivetran-joemarkiewicz - I have not had the chance. I don't want to hold this feature up for others so if you are able to bring it in, that would be great!

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for the quick reply! Our current sprint just kicked off, but I will add this to our upcoming sprint task list.

**Comment by ron-eventgroove** [comment]
Awsome, thanks @fivetran-joemarkiewicz!

**Comment by skalepp-parachutehome** [comment]
@fivetran-joemarkiewicz  - Was this brought into the sprint?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @skalepp-parachutehome and @ron-eventgroove 👋 

I have been able to get a working version of the package with this new feature included to filter out specified email events. I will kick off our internal review process shortly, but it would be great if either of you have time to test the working version of the package and confirm the email events are being properly filtered out when defining the new `hubspot_using_filtered_events` variable as `false`.

You can test the branch with the changes by using the following in your `packages.yml` in place of the current hubspot version.
```yml
packages:
  # You can comment out the official version for the time being
  # - package: fivetran/hubspot
  #   version: [">=0.9.0", "<0.10.0"]

  - git: https://github.com/fivetran/dbt_hubspot.git
    revision: feature/email-event-filter
    warn-unpinned: false 
```

Once you have this updated, be sure to save and then include the following variable in your `dbt_project.yml`.

```yml
vars:
  hubspot_using_filtered_events: false # True by default
```

After the above are applied, you can re run `dbt deps` and run the package models to see if the filtered events are properly being removed in your downstream models. Let me know if you are able to test and how it goes!

**Comment by fivetran-joemarkiewicz** [comment]
This has been incorporated in the latest release. As such, I will close this feature request.
