### ISSUE TITLE
[Bug] The hubspot__contacts calls upon the contact_merge_audits even though the table has been deprecated from the connector

### ISSUE THREAD

**Issue by elanfivetran** [fivetran/dbt_hubspot#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Per the [HubSpot Release Notes](https://fivetran.com/docs/applications/hubspot/changelog), Fivetran deprecated the `CONTACT_MERGE_AUDIT` table.

However, in the **hubspot__contacts.sql** model that exists in this package the `CONTACT_MERGE_AUDIT` table is still being referenced if `hubspot_contact_merge_audit_enabled` is marked as `True` in **dbt_project.yml**. Since most users moving forward will not have the `CONTACT_MERGE_AUDIT` in their schema, `hubspot_contact_merge_audit_enabled` should have a default of `False`. 

### Expected behavior

Since most users moving forward will not have the `CONTACT_MERGE_AUDIT` in their schema, `hubspot_contact_merge_audit_enabled` should have a default of `False`. 

### dbt Project configurations

They are configured to the default settings. 

### Package versions

n/a

### What database are you using dbt with?

bigquery

### dbt Version

n/a

### Are you willing to open a PR to help address this issue?

- [ ] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [X] No.

**Comment by fivetran-reneeli** [comment]
Following office hours with customer running into duplicates resulting from the same issue, tagging @uxdi-rajan here

**Comment by fivetran-jamie** [comment]
the fix for this should officially be in v0.9.0 of the package!

**Comment by uxdi-rajan** [comment]
Thank you guys for working on this. Appreciate it!
